const ASSET_STATUSES = ['IN_OFFICE', 'OUTSIDE', 'RETURNED', 'MAINTENANCE', 'LOST'];
const LOG_STATUSES = ['OUT', 'IN'];
const ADMIN_ROLES = ['SUPER_ADMIN', 'ASSET_MANAGER', 'RECEPTION'];

module.exports = { ASSET_STATUSES, LOG_STATUSES, ADMIN_ROLES };
